
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config #name of configmap
  namespace: default #namespace 
data:
  special.how: very # literal data 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  # example of a complex property defined using --from-file
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3
